### ISSUE TITLE
Make pip understand the version set for fileflow

### ISSUE THREAD

**Issue by lauralorenz** [industrydive/fileflow#7]
Something is wrong with the version number when trying to install fileflow in that it thinks its 0.0.0 even though our setup.cfg, at time of writing, sets it to 0.0.3. Not sure if this is a property of the git install and/or if this will cause problems with later installs since we're installing from commit hashes, but I think worth figuring out including how it may interact with PyPI packages.

```
(fileflow)~ $ pip freeze | grep fileflow
You are using pip version 6.0.8, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
fileflow==0.0.0
```

**Comment by ksindi** [comment]
Awesome project. For easier version management, I recommend using [setuptools_scm](https://github.com/pypa/setuptools_scm), which allows you to use your git / mercurial tags for versioning.

**Comment by lauralorenz** [comment]
@ksindi great suggestion, we will check it out

**Comment by lauralorenz** [comment]
This was fixed by https://github.com/industrydive/fileflow/pull/11.
