### ISSUE TITLE
Working example with fileflow

### ISSUE THREAD

**Issue by ThetomekK** [industrydive/fileflow#8]
Hi Laura, 

This is not an issue, but could you add a example to the docs, how exactly to use fileflow? 

This would be extremely helpful, especially to understand major differences or advantages of airflow+fileflow compared to Luigi. 

Watched your talk, and the question came up, thank you!

**Comment by lauralorenz** [comment]
@ThetomekK definitely, will do asap :+1:

**Comment by lauralorenz** [comment]
FYI @ThetomekK I'm working on it over at https://github.com/industrydive/fileflow/pull/9/files but need to pretty it up a bit. But if you wanted to see the example before I check the sphinx rendering you can see it there.
